### ISSUE TITLE
Server hangs on MacOs if /var/lib/bblfshd is mounted

### ISSUE THREAD

**Issue by smacker** [bblfsh/bblfshd#136]
Any ideas how to debug?

if I start bblfshd like this
```
docker run -d --name bblfshd --privileged -p 9432:9432 -v $(pwd)/bblfshd-data:/var/lib/bblfshd bblfsh/bblfshd
```

and then call "parse" method - server never respond. No matter do I do call inside or outside container `docker exec -it bblfshd bblfshctl parse /opt/bblfsh/etc/examples/python.py` || using dashboard.

After that I'm unable to do anything with container `docker stop` & `docker kill` just hangs forever. Only restarting all docker helps.

But if I run bblfshd without mounting 
```
docker run -d --name bblfshd --privileged -p 9432:9432 bblfsh/bblfshd
```
everything works fine.

I undestand that issue description isn't very helpful, but I don't know how to collect more information.

**Comment by juanjux** [comment]
Probably duplicated of bblfsh/python-driver/issues/128.

We've a Doc PR needing merge for using a docker volume instead of a mount point, please tell me if it works for you and I'll merge:

https://github.com/bblfsh/documentation/pull/121/files
