### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by smacker** [bblfsh/bblfshd#143]
Is there any plans to measure how fast bblfsh and drivers work and improve it?
I thought to use it in my project, but it works very slow.

Currently, the difference bblfsh vs native parser is huge.
Example of parsing `itsdangerous.py` 500 times:

native parser:
```python
import ast
from datetime import datetime

st = datetime.now()

for _ in range(500):
    tree = ast.parse(open('itsdangerous.py').read())
    ast.dump(tree)

print(datetime.now() - st)
```

using bblfs:
```go
package main

import (
	"fmt"
	"io/ioutil"
	"time"

	"gopkg.in/bblfsh/client-go.v2"
)

const times = 500

func main() {
	b, err := ioutil.ReadFile("itsdangerous.py")
	if err != nil {
		panic(err)
	}
	content := string(b)

	client, err := bblfsh.NewClient("0.0.0.0:9432")
	if err != nil {
		panic(err)
	}

	st := time.Now()

	for i := 0; i < times; i++ {
		_, err = client.NewParseRequest().Language("python").Content(content).Do()
		if err != nil {
			panic(err)
		}
	}

	fmt.Println(time.Now().Sub(st))

}
```

Results:
```
$ python3 parse.py
0:00:09.097725

$ go run main.go
2m34.900917922s
```

9s vs 2m34s is kinda huge...

Will you be open to my help with profiling/optimization?

**Comment by juanjux** [comment]
The native parse is implemented in pure C. The non native parse must do a second pass to add missing positions (the ones we can), comments, et cetera, so it's much slower. Then you need to add the protocol round trip, once for the client to the server and another one from the server to the driver... you get the picture. Still, at some point we should need to benchmark every part and find fixable bottlenecks.

**Comment by smacker** [comment]
Thank you for replay. I perfectly understand why it’s slower.
My question is: do you have performance improvements in roadmap? If not, will you be open to pull requests with profiling/benchmarks/optimizations?

I’m sorry if it wasn’t clear from my first message.

**Comment by mcuadros** [comment]
We never get focused on performance, the last improvements we did were focused on resilience. 

Said this, as @juanjux explained, what you are obtaining from the python AST is not the same information you get from the bblfshd server.  Also, you executed this on linux or macOS?

Also, this metrics are for Python, so maybe is the driver, maybe is the server, etc. Definitely, we should get some profiling stats, to at least know how many time takes each part.i

For sure can be improved and we should improve, but at least in the latest metrics I got from engine, bblfshd is not being the bottleneck at all.

**Comment by smacker** [comment]
Okay. Not in roadmap. Thanks!

Let me give more context. I'm working on `hercules-web` during OSDs. I want to calculate function hotness. But it's way too slow for web service even for small repos.
I wanted to spend my next OSDs writing some benchmarks and try to optimize it.

But very often performance optimizations add complexity to code. Can I expect such PRs to be merged or if it's totally not a focus will it be rejected?

**Comment by juanjux** [comment]
Some ideas for that OSD:

- Benchmark also against connecting directly to the driver via gRPC (just run the driver image and connect to it, it speaks the same protocol as the server). This will give the load bblfshd adds.

- Benchmark the Python, Java and Scala drivers with files of more or less the same complexity. 

- Hack the native drivers a little for them do to their parse in a loop without any gRPC calling.

- Compare the speed of Parse vs ParseNative. This would give the load added by the annotating process.

**Comment by juanjux** [comment]
Out of focus PRs won't be rejected, the focus is for the language-analysis team planned tasks/epics and doesn't apply to contributions from other teams or OSDs.

**Comment by smacker** [comment]
Thanks a lot! My own thoughts how to do it are very similar :)
I just don't think I need to `hack the native drivers`. Every driver has cli tool which reads from stdin. I can use it!

**Comment by smacker** [comment]
got some results: https://github.com/smacker/bblfsh-benchmark
