### ISSUE TITLE
Not Able to execute the the test command as per the getting started guide

### ISSUE THREAD

**Issue by vasulakkaraju** [bblfsh/bblfshd#146]
Testing Babelfish drivers as per the getting started guide.But getting below error while testing:

command:

sudo docker exec -it bblfshd bblfshctl parse /opt/bblfsh/etc/examples/python.py

Status: Fatal
Elapsed: 5.000365287s
Errors:
	- timeout, all drivers are busy
pls help me if its an issue.

Thanks.

**Comment by juanjux** [comment]
I can't reproduce this.

Did you followed these steps?

1. Install and run the server with:

```docker run -d --name bblfshd --privileged -p 9432:9432 bblfsh/bblfshd```

2. Install the recommended drivers with:

``` docker exec -it bblfshd bblfshctl driver install --recommended```

3. Run the example:

``` docker exec -it bblfshd bblfshctl parse /opt/bblfsh/etc/examples/python.py```

If this still fails, please tell me the operating system that you're running (and Linux distribution if you're under Linux) and the output of:

```docker exec -it bblfsh bblfshctl driver list```

**Comment by juanjux** [comment]
I'll see if I can reproduce it with a Fedora 27 LXC image.

**Comment by vasulakkaraju** [comment]
Sure!

**Comment by juanjux** [comment]
Hi @vasulakkaraju, sorry for not replying before, I've been busy with the bash driver, I'll try to reproduce your problem in the Fedora 27 image right now.

About your question, there are clients for [Python](https://github.com/bblfsh/client-python), [Scala](https://github.com/bblfsh/client-scala) and [Go](https://github.com/bblfsh/client-go) that you can use to do requests to the server or driver (drivers can be run without the server, with the same gRPC interface) and get the UAST as a data structure. Then you can use the `filter()` method to apply XPath filtering to the returned AST and get specific nodes or tokens, check the docs here: https://doc.bblf.sh/user/uast-querying.html.

**Comment by juanjux** [comment]
@vasulakkaraju could you run `docker logs bblfshd` after you get the error and paste the output here?

**Comment by Morikko** [comment]
Got the same problem (Fedora 27):

### First try 
```bash
$> docker exec -it bblfshd bblfshctl parse /opt/bblfsh/etc/examples/python.py
Status: Fatal
Elapsed: 124.445374ms
Errors:
	- unexpected error: container_linux.go:296: starting container process caused "permission denied"
```
### Further tries
```bash
$> docker exec -it bblfshd bblfshctl parse /opt/bblfsh/etc/examples/python.py
Status: Fatal
Elapsed: 5.00086396s
Errors:
	- timeout, all drivers are busy
```

### Your request
```bash
$> docker logs bblfshd
time="2018-02-26T10:15:01Z" level=info msg="bblfshd version: v2.4.0 (build: 2018-02-21T18:11:17+0000)"
time="2018-02-26T10:15:01Z" level=info msg="initializing runtime at /var/lib/bblfshd"
time="2018-02-26T10:15:01Z" level=info msg="control server listening in /var/run/bblfshctl.sock (unix)"
time="2018-02-26T10:15:01Z" level=info msg="server listening in 0.0.0.0:9432 (tcp)"
time="2018-02-26T10:15:59Z" level=info msg="driver java installed "bblfsh/java-driver:latest""
time="2018-02-26T10:16:15Z" level=info msg="driver javascript installed "bblfsh/javascript-driver:latest""
time="2018-02-26T10:16:29Z" level=info msg="driver typescript installed "bblfsh/typescript-driver:latest""
time="2018-02-26T10:18:19Z" level=info msg="driver python installed "bblfsh/python-driver:latest""
time="2018-02-26T10:18:51Z" level=info msg="driver ruby installed "bblfsh/ruby-driver:latest""
time="2018-02-26T10:19:04Z" level=info msg="driver go installed "bblfsh/go-driver:latest""
time="2018-02-26T10:19:27Z" level=info msg="driver php installed "bblfsh/php-driver:latest""
time="2018-02-26T10:20:12Z" level=info msg="driver bash installed "bblfsh/bash-driver:latest""
panic: permission denied
goroutine 1 [running, locked to thread]:
github.com/bblfsh/bblfshd/runtime.Bootstrap()
	/go/src/github.com/bblfsh/bblfshd/runtime/runtime.go:198 +0x15d
main.init.0()
	/go/src/github.com/bblfsh/bblfshd/cli/bblfshd/main.go:61 +0x499
main.init()
	<autogenerated>:1 +0x7b
time="2018-02-26T10:22:11Z" level=error msg="error selecting pool: unexpected error: container_linux.go:296: starting container process caused "permission denied""
time="2018-02-26T10:22:11Z" level=error msg="request processed content 23 bytes, status Fatal" elapsed=124.445374ms filename=python.py language=
time="2018-02-26T10:23:03Z" level=warning msg="unable to allocate a driver instance: timeout, all drivers are busy" language=python
time="2018-02-26T10:23:03Z" level=error msg="request processed content 23 bytes, status Fatal" elapsed=5.00086396s filename=python.py language=python
```

**Comment by juanjux** [comment]
Thanks for the log @Morikko; so it definitely looks like it's a problem that triggers with Fedora 27. I'll revisit this today (tried with an LXD image but had some problems running Docker inside it, I'll try again today with Vagrant).

**Comment by juanjux** [comment]
Semi-good news, I can reproduce it (with the same log) in a Fedora 27 image. I'll continue looking into it.

**Comment by Morikko** [comment]
> maybe some SELinux configuration?

I thought also to this. However, I got the same result by setting `setenforce 0` (normally set SELinux in permissive mode)

I didn't investigate further...

**Comment by juanjux** [comment]
Yes, I disabled SELinux and the problem persists here too. Another odd problem: if I do a `docker restart bblfsdh` it says:

```
time="2018-02-27T18:53:27Z" level=error msg="error creating control listener: listen unix /var/run/bblfshctl.sock: bind: address already in use"
```

But the socket file doesn't exist...

**Comment by juanjux** [comment]
I wasn't disabling SELinux correctly, and actually setting permissive mode fixed the problem, but only after deleting and reinstalling `bblfshd`, the steps I followed to make it work:

```
echo 0 > /sys/fs/selinux/enforce
docker rm -f bblfshd
docker run -d --name bblfshd --privileged -p 9432:9432 -v /var/lib/bblfshd:/var/lib/bblfshd bblfsh/bblfshd
docker exec -it bblfshd bblfshctl driver install --recommended
```

**Comment by juanjux** [comment]
@Morikko @vasulakkaraju check the PR above, it adds a SELinux policy file and instructions about how to use it.
