### ISSUE TITLE
Installation of ruby driver fails

### ISSUE THREAD

**Issue by EgorBu** [bblfsh/bblfshd#156]
Hi,
I noticed that installation of ruby driver failed.
How to reproduce:
```bash
$ docker run -d --name bblfshd --privileged -p 9432:9432 bblfsh/bblfshd
```
and 
```bash
$ docker exec -it bblfshd bblfshctl driver install --recommended
```
It gives:
```
Installing python language driver from "docker://bblfsh/python-driver:latest"... Done
Installing java language driver from "docker://bblfsh/java-driver:latest"... Done
Installing php language driver from "docker://bblfsh/php-driver:latest"... Done
Installing go language driver from "docker://bblfsh/go-driver:latest"... Done
Installing javascript language driver from "docker://bblfsh/javascript-driver:latest"... Done
Installing ruby language driver from "docker://bblfsh/ruby-driver:latest"... Error
Error, unable to delete whiteout path: lstat /var/lib/bblfshd/tmp/image775651636/usr/lib/ruby/gems/2.3.0/gems/ast-2.4.0/.wh..opq: operation not permitted
```

**Comment by juanjux** [comment]
Note for further debugging and helping users with the problem workaround it: it only happens when docker-running bblfshd without the `-v /var/lib/bblfshd:/var/lib/bblfshd` option.

**Comment by dpordomingo** [comment]
It happened to me with Python driver too
```shell
> docker run --privileged -d -p 9432:9432 --name bblfsh bblfsh/bblfshd
db254374faed67537ac3848bec8fe82599ec21ff5e3fe04b3d1d274cbbd3e37d

> docker exec -it bblfsh bblfshctl driver install --recommended
[...]
Installing python language driver from "docker://bblfsh/python-driver:latest"... Error
Error, unable to delete whiteout path: lstat /var/lib/bblfshd/tmp/image460726411/usr/lib/python3.6/site-packages/pydetector/.wh..opq: operation not permitted
```

**Comment by dpordomingo** [comment]
It was fixed when I ran the `bblfsh` container with `-v /var/lib/bblfshd:/var/lib/bblfshd`

To reproduce the problem **again** I deleted the whole content of `/var/lib/bblfshd`, and the `bblfsh` container, and ran it again without mounting the volume. If I do so, python and ruby drivers installation fails.

**Comment by EgorBu** [comment]
I have this problem again - but today not only [`ruby`](https://github.com/bblfsh/ruby-driver/issues/22) but [`python`](https://github.com/bblfsh/python-driver/issues/156) too

**Comment by dpordomingo** [comment]
@EgorBu did you tried running docker with `-v /var/lib/bblfshd:/var/lib/bblfshd` ?
If running it from Mac, it is needed to follow other instruction (described in [doc.bblf.sh/getting-started](https://doc.bblf.sh/user/getting-started.html)

**Comment by EgorBu** [comment]
@dpordomingo, yes, with attached volume it works but it should be possible to install everything without attached volume. I'm using Ubuntu.

**Comment by dpordomingo** [comment]
maybe @juanjux could clarify if the mounting procedure is the recommended way to run bblfsh

**Comment by dennwc** [comment]
It's the required way right now, but it shouldn't be a requirement. We need to examine what permission bits are set by drivers to their dependencies. to fix this.

**Comment by dennwc** [comment]
Please try to reproduce it with `v2.1.1` drivers.

**Comment by dennwc** [comment]
Ping @EgorBu

**Comment by dennwc** [comment]
I assume this was fixed
