### ISSUE TITLE
Some lang names guessed by bblfsh has a different driver name

### ISSUE THREAD

**Issue by dpordomingo** [bblfsh/bblfshd#162]
When sending to bblfsh a code with a filename `whatever.sh`, it is tried to be parsed with `shell` driver, but this driver should be identified as `bash`; when it happens, the request fails because bblfsh is not able to route `shell` requests to `bash` driver.

As suggested by @juanjux (via Slack), it could be interesting to have language aliases defined in the driver's manifest and then bblfshd could read and route those names to the proper driver.

**Comment by dennwc** [comment]
@juanjux Maybe we should rename the driver to `shell`?

**Comment by smola** [comment]
The Bash driver should work with any valid Bash subset, it would even support most code for Zsh, which is not a subset but it's pretty similar. That covers most shells and most shell code. However, I think it will never support csh/tcsh syntax.

Whatever solution you pick, I think it's safe to assume that the Bash driver is everything we'll need for shell language in the foreseeable future.

**Comment by juanjux** [comment]
We spoke some time ago about supporting more language aliases in the manifest to cover drivers supporting more languages (like Python2/3, TypeScript/Javascript, etc). But while we do that I'm ok with renaming to Shell if we agree.

**Comment by dennwc** [comment]
I think renaming to `shell` is the best option for now. And it seems like we all agree on this.

@juanjux Can you please rename the driver and change the GitHub project tags to `shell`?

**Comment by juanjux** [comment]
Will do.

**Comment by smola** [comment]
@juanjux @dennwc I was discussing with Máximo, I'm cc'ing him (@mcuadros) to comment on the alternative of keeping the driver as `bash-driver` and defining an alias for the Shell language.

**Comment by mcuadros** [comment]
The name of the drivers are the name of a language, `shell` is not a language name, so we should keep the name of 'bash', what we can do... if worth it, is identify bash in Enry, but this is not a bblfsh issue
