### ISSUE TITLE
Flacky behavior in CI

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/bblfshd#165]
This is what I occasionally get in Travis:

```
docker exec -it bblfshd bblfshctl driver install --all
Error, GET https://api.github.com/orgs/bblfsh/repos?page=1&per_page=100&type=public: 403 API rate limit exceeded for 35.188.1.99. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 11m33s]
```

This prevents my tests from running :(

**Comment by dennwc** [comment]
@vmarkovtsev Do you really need all languages for the test? Maybe you can narrow it down to few specific languages?

**Comment by smola** [comment]
There is a good case for us to generate a static manifest that can be consumed by bblfshd without using GitHub API.

**Comment by dennwc** [comment]
@smola Sure, but we don't want to maintain it manually. We will need a webhook for this.

**Comment by smola** [comment]
@dennwc We can probably setup a Travis CI job that generates and updates the manifest. Then we could add a post-deploy Travis hook for drivers that trigger the manigest job through Travis API.

**Comment by bzz** [comment]
Just FYI - that has been discussed on a recent [TL meeting](https://github.com/src-d/minutes/pull/263/files#diff-c9b1efc76d1d61c3077a03a37d67be6eR78) and the decision was to pin only a specific drivers + mount them and cache those on TravisCI. 

That’s what being used so far i.e in [gitbase playground](https://github.com/src-d/minutes/pull/263/files#diff-c9b1efc76d1d61c3077a03a37d67be6eR78).

**Comment by dennwc** [comment]
It seems like the issue is solved.

If changes to discover discovery are still necessary - please open a separate issue in the SDK.
