### ISSUE TITLE
`Error` -> `Warning` when driver is already installed

### ISSUE THREAD

**Issue by EgorBu** [bblfsh/bblfshd#166]
Hi,
I think it's better to change `error` to `warning` when driver is already installed,  `error` message is very confusing in this case because nothing is broken.
```
Installing go language driver from "docker://bblfsh/go-driver:latest"... Done
Installing java language driver from "docker://bblfsh/java-driver:latest"... Error
Error, driver already installed: java (image reference: bblfsh/java-driver:latest)
Installing bash language driver from "docker://bblfsh/bash-driver:latest"... Done
Installing php language driver from "docker://bblfsh/php-driver:latest"... Done
Installing python language driver from "docker://bblfsh/python-driver:latest"... Error
Error, driver already installed: python (image reference: bblfsh/python-driver:latest)
Installing javascript language driver from "docker://bblfsh/javascript-driver:latest"... Done
Installing ruby language driver from "docker://bblfsh/ruby-driver:latest"... Done
```

**Comment by dennwc** [comment]
This error is returned across an RPC boundary, so we need to return a different gRPC status code, and convert it on the client side.

Converting to a warning makes sense only when the hash of the local image matches the hash of the remote image. In other cases we are not sure what user expects us to do. An image might be a dev image built locally, and we don't know if we should reinstall it from remote or not.

@juanjux What do you think?

**Comment by juanjux** [comment]
I think it's an Error... the user asked to install an image, and it could not be installed. A warning would be, IMO, to overwrite an existing image.

**Comment by dennwc** [comment]
Maybe we should convert it to Warning only for the batch commands like `--recommended`?

**Comment by juanjux** [comment]
That would make sense, yes.

**Comment by dennwc** [comment]
It will now happen with `driver install` for a single driver as well, see #195. This error was not propagated correctly.
