### ISSUE TITLE
Latest release doesn't have correct binaries

### ISSUE THREAD

**Issue by ajnavarro** [bblfsh/bblfshd#192]
Check https://github.com/bblfsh/bblfshd/releases/tag/v2.8.0

**Comment by dennwc** [comment]
It also failed to produce an image with embedded drivers.

**Comment by dennwc** [comment]
Still unresolved

**Comment by bzz** [comment]
@ajnavarro was published https://github.com/bblfsh/bblfshd/releases/tag/v2.9.1 with the binaries

**Comment by ajnavarro** [comment]
@bzz Windows and darwin binaries are still bad.

**Comment by bzz** [comment]
Oh, wow, 🤦‍♂️ 

It would be nice to migrate bblfsd [Makefile](https://github.com/bblfsh/bblfshd/blob/master/Makefile) to src-d/ci v1.

@dennwc if you want, I can take a look into this.

**Comment by dennwc** [comment]
@bzz Thanks, I will appreciate it :)

**Comment by bzz** [comment]
@dennwc fix is in #204 / #205 - as soon as it's reviewed&merged I would be happy to cut a new release in order to verify it.
