### ISSUE TITLE
Ensure exported names in Go packages are properly documented

### ISSUE THREAD

**Issue by creachadair** [bblfsh/bblfshd#211]
There are a number of packages missing conventional documentation comments (cf. https://github.com/golang/go/wiki/CodeReviewComments#doc-comments). Given that we advertise these libraries as part of an SDK, we should make an effort to back-fill the ones that are missing.

This helps not only us (speaking as the new person trying to learn his way around), but also our users, who should be able to use godoc.org to good effect.

**Comment by bzz** [comment]
👍 and we could also enable `go lint` with [this check](https://github.com/golang/lint/blob/master/lint.go#L476) on CI, to avoid further API doc gaps.

**Comment by creachadair** [comment]
The `golint` checks are mostly good, but there are enough false positives that I'd be reluctant to block changes for all of them. That said, I agree it'd be nice to have some pre-submit linting suggestions.

**Comment by dennwc** [comment]
We may disable most `golint` checks and leave only ones related to documentation, for example.
