### ISSUE TITLE
How to make sure Standalone installation of bblfshd daemon runs in background

### ISSUE THREAD

**Issue by deepakorantak** [bblfsh/bblfshd#221]
I have  successfully installed (from standalone binaries on github )  and the executables are in/usr/local/bin so that I can execute it from anywhere.

root@ip-172-31-34-50:/usr/local/bin# ls -a bbl
bblfshctl  bblfshd

### When I execute any of the _bblfshctl_ commands  it throws following  error -

root@ip-172-31-34-50:/usr/local/bin# bblfshctl driver list
**failed to connect to /var/run/bblfshctl.sock (unix): timeout**

Usage:
  bblfshctl [OPTIONS] driver list [list-OPTIONS]

List the installed drivers for each language

Help Options:
  -h, --help              Show this help message

[list command options]
          --ctl-endpoint= control server network type (default: unix)
          --ctl-address=  control server address to connect (default: /var/run/bblfshctl.sock)

Build information
  commit: v2.9.2
  date: 2018-10-26T16:17:02+00:00

### If I start the daemon using command - _bblfshd_  it's not executed in background so can not execute the _bblfshctl_  commands -

root@ip-172-31-34-50:/usr/local/bin# bblfshd
[2018-11-23T10:22:57Z]  INFO bblfshd version: v2.9.2 (build: 2018-10-26T16:16:27+00:00)
[2018-11-23T10:22:57Z]  INFO initializing runtime at /var/lib/bblfshd
[2018-11-23T10:22:57Z]  INFO control server listening in /var/run/bblfshctl.sock (unix)
[2018-11-23T10:22:57Z]  INFO server listening in 0.0.0.0:9432 (tcp)

^C[2018-11-23T10:23:07Z]  WARN signal received interrupt
[2018-11-23T10:23:07Z]  WARN stopping server
[2018-11-23T10:23:07Z] ERROR error starting control server: accept unix /var/run/bblfshctl.sock: use of closed network connection

===================================================================

so want to know how the bblfshd can be run in background ?

**Comment by bzz** [comment]
hey @deepakorantak -  to get bblfshd process running on *nix OS in terminal on [background](https://bash.cyberciti.biz/guide/Putting_jobs_in_background#Background_process) launch it with `bblfshd &`.

Hope this helps!

**Comment by deepakorantak** [comment]
Thank you so much @bzz . It worked !!
