### ISSUE TITLE
bblfshctl does not return an error code if it fails to install a driver

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/bblfshd#223]
Docker Hub is [experiencing problems right now](https://github.com/docker/hub-feedback/issues/1693) and our Travis jobs started to fail.

For example: https://travis-ci.org/src-d/style-analyzer/jobs/459372829#L600

```
docker exec style_analyzer_bblfshd bblfshctl driver install \
	javascript docker://bblfsh/javascript-driver\:v1.2.0
Installing javascript language driver from "docker://bblfsh/javascript-driver:v1.2.0"... | Error, error parsing HTTP 404 response body: invalid character 'p' after top-level value: "404 page not found\n"
```

This command succeeds or fails depending on your luck.
Unfortuntely, `bblfctl` still returns a 0 status code and I have to work around it in order to use `travis_retry`.

**Comment by vmarkovtsev** [comment]
Bump on this

**Comment by dennwc** [comment]
After trying for a few hours, I neither can reproduce it, nor find by analyzing the source.

According to CI log, you are using an ancient bblfshd version (`v2.5.0`). Is there any specific reason for this? We may have already fixed this upstream.

**Comment by dennwc** [comment]
Can confirm that it returns the code correctly on `bblfshd:latest` and returns `exit 0` on `bblfshd:v2.5.0`.

**Comment by vmarkovtsev** [comment]
Thanks for investigating, we will update. If the problem persists, I will reopen.

**Comment by vmarkovtsev** [comment]
@zurk Can you please update bblfshd in our CIs everywhere and wrap bblfshctl calls in travis_retry

**Comment by zurk** [comment]
already bumped, will wrap.
