### ISSUE TITLE
Unable to allocate a driver instance: timeout, all drivers are busy

### ISSUE THREAD

**Issue by ajnavarro** [bblfsh/bblfshd#227]
On gitbase we are having the following error if we try to parse more than 1000 files:

`bblfshd     | time="2018-11-30T13:13:35Z" level=warning msg="unable to allocate a driver instance: timeout, all drivers are busy" language=go`

https://github.com/src-d/gitbase/issues/634

Even changing the request timeout we still have the error.

Is this timeout a different one? If yes, is it possible to change from the client side?

**Comment by smola** [comment]
I wonder if clients need to distinguish this timeout from others or not, I can think about a couple of solutions:

- Make this timeout an error with a specific gRPC code, clients are meant to retry.
- Remove this error completely, use client's context, and if context deadline exceeded, possibly include in the message whether the timeout was while waiting for a driver or while parsing.

**Comment by dennwc** [comment]
I think using the client's context is the right way to do it. "Failed to parse" and driver failures are the only error client don't want to retry, and everything else is probably time-related. And we have error codes for both, I believe.

**Comment by creachadair** [comment]
Agreed the client's context should govern the request. As much as possible we should avoid having "internal" timeouts for things. Any such timeouts wind up affecting the "signature" of the API and the caller has to be aware of them and know what to do.
