### ISSUE TITLE
Add C# driver to install --all

### ISSUE THREAD

**Issue by smacker** [bblfsh/bblfshd#235]
The driver is in alpha/beta stage already and usable. But isn't available to install anyhow but manually.

**Comment by smacker** [comment]
Copy-past from slack as Alex requested:

> Yes. But may we have added it to “all” instead of doing workarounds on infra side? Manual installation isn’t an option because pods get restarted. (For example I forgot to re-install it manually the last time it got restarted and 30+h run of Gemini didn’t extract features from C# files)

**Comment by juanjux** [comment]
Probably once we merge this, which should be Real Soon Now :tm:  since it has a gazillion fixes:

https://github.com/bblfsh/csharp-driver/pull/17

**Comment by juanjux** [comment]
csharp-driver 1.0 have been published and now the csharp driver is installed both by `bblfshctl driver install --recommended` and `--all`.
