### ISSUE TITLE
Investigate the feasibility of a PL/SQL driver

### ISSUE THREAD

**Issue by creachadair** [bblfsh/bblfshd#237]
Many enterprises use PL/SQL as a convenient mechanism for integrating computation with their database infrastructure. The existence of large in-house PL/SQL codebases presents an interesting tooling problem for those companies.

Investigate whether a Babelfish driver for PL/SQL is practical. Ideally we'd want a solution that is based on an open-source toolchain, in preference to rolling our own.

Some starting points:

* [Database PL/SQL Language Reference][langref] (Oracle).
* [Semantic Designs PL/SQL Parser][sdparser].

[langref]: https://docs.oracle.com/cd/B28359_01/appdev.111/b28370/toc.htm
[sdparser]: http://www.semdesigns.com/Products/FrontEnds/PLSQLFrontEnd.html?Home=FrontEnd

**Comment by creachadair** [comment]
Another [list of PL/SQL tools](https://docstore.mik.ua/orelly/oracle/webapp/ch06_04.htm). I have not followed up on most of these yet.

**Comment by eiso** [comment]
Any update here?

**Comment by creachadair** [comment]
> Any update here?

Not yet, I got derailed by other things. I'll post an update by EoW.

**Comment by creachadair** [comment]
Update: Slim pickings. Lots of noise, but very little utility.

I spent some quality time trawling search results for PL/SQL and related queries. **In summary:** There are a lot of tools available for PL/SQL, but very little that will be of use to us. Even Oracle, who is probably the largest driver of PL/SQL (via its products that support it) does not appear to offer libraries for parsing or manipulating the language as an artifact in itself: https://www.oracle.com/database/technologies/appdev/plsql.html. I was a little reluctant to adopt anything controlled by Oracle anyway, given their litigious history, but it doesn't seem to matter. The party line is that [Oracle SQL Developer](https://www.oracle.com/database/technologies/appdev/sql-developer.html) is "free", but it is an application rather than a library, is not open-source, and requires acceptance of the [OTN license](https://www.oracle.com/technetwork/licenses/sqldev-license-152021.html) which, among other things, precludes modification, redistribution, reverse-engineering, and fun of any kind involving the product, so I would say this is a non-starter for us.

I also looked at a number of "third" party tools (though practically speaking ~everything about PL/SQL is third-party since the only native compiler I was able to find was [Oracle's](https://oracle-base.com/articles/9i/plsql-native-compilation-9i)). The majority of these are packaged applications, whose source is not readily available (e.g., Benthic SQALL https://www.benthicsoftware.com/), and most seem to be specific to Windows.

There is a [Go lexer built around ANTLR4](https://godoc.org/bramp.net/antlr4/plsql) that looks reasonable but doesn't handle syntactic structure. Taking a dependency on ANTLR is a bit of a rathole, but this could possibly be useful as a starting point.

[Semantic Designs](http://www.semdesigns.com/Products/FrontEnds/SQLFrontEnd.html?Home=PLSQLFrontEnd) advertises some PL/SQL parser, formatter, style-checker type [tools](http://www.semdesigns.com/Products/Tools.html) that can be downloaded after signing an [evaluation agreement](http://www.semdesigns.com/Products/EvalLicense-download.pdf). I have not yet done this, but am considering asking for an eval so we can at least see if it does something useful. It does not appear to be in any way open-source, though.

Right now, it appears the most viable path forward for us to support PL/SQL would be to write a parser of our own. There is an [ANTLR grammar](https://github.com/antlr/grammars-v4/tree/master/plsql) for PL/SQL, though I do not know how compliant it is. The [Oracle spec](https://docs.oracle.com/cd/B28359_01/appdev.111/b28370/toc.htm) gives an informal description of the language but no precise grammar, so it will be a bit of shovel-work if we want to build something on top of that.

**Comment by eiso** [comment]
Building one of our own. What's the kind of effort it would take? I'll reach out to the CEO of Semantic Designs too.

**Comment by creachadair** [comment]
> Building one of our own. What's the kind of effort it would take? I'll reach out to the CEO of Semantic Designs too.

For a language (other than C++) with a well-documented grammar, it would be not that much work to generate a parser: A couple weeks of work, I would estimate, to put it together and shake out the basic operability issues. However, the PL/SQL grammar is defined [informally](https://docs.oracle.com/cd/B28359_01/appdev.111/b28370/langelems.htm#LNPLS013), in discursive Enterprise Language™, and the specification provides no compatibility tests (though perhaps they do if one pays for the product).

So in this case it's a bit unknown. PL/SQL doesn't appear in the ANSI SQL standards, but my next plan is to investigate extending an existing ANSI SQL parser (I have my eye on the one from Vitess) with some productions back-ported from the PL/SQL docs. No real idea whether that will work, but it looks like the best available path forward at the moment.

**Comment by juanjux** [comment]
If we're building our own parser we could also take a look at PEG style parsers, which I personally like a lot. [This one](https://github.com/PhilippeSigaud/Pegged) in particular is amazing because it generates the parser from the grammar at compile time.
