### ISSUE TITLE
Language aliases support

### ISSUE THREAD

**Issue by bzz** [bblfsh/bblfshd#263]
Enry and Bblfsh use different language names and one driver is responsible for parsing multiple dialects.

Right now bblfsh can accept both bblfsh or enry language names (for most common cases), but returns always only bblfsh ones.

Initial RFC and implementation details are in [mailing list](https://groups.google.com/forum/#!topic/bblfsh-dev/mo1o5d_CwnA)

This issue is going to be used as ☂️ and all details from MailingList will be moved in here before actual work begins (current expectation is `2Q2019`).

## Driver → Language Aliases

 - [bash](https://github.com/bblfsh/bash-driver)
     * shell
     * TODO: add more *sh that enry differenciate
 - [cpp](https://github.com/bblfsh/cpp-driver)
     * C
     * C++
 - [csharp](https://github.com/bblfsh/csharp-driver)
     * C#
 - [Go](https://github.com/bblfsh/go-driver)
 - [Java](https://github.com/bblfsh/java-driver)
 - [JavaScript](https://github.com/bblfsh/javascript-driver)
    * JSX
    * Javascript
 - [PHP](https://github.com/bblfsh/php-driver)
 - [Python](https://github.com/bblfsh/python-driver)
 - [Ruby](https://github.com/bblfsh/ruby-driver)
 - [TypeScript](https://github.com/bblfsh/typescript-driver)

This list covers 2 main cases:
 1. `enry` <=> `bblfshd` language name mismatch (e.g `C#` vs `charp`)
 2. Dialects supported by a single driver (e.g `javascript-driver` for JSX and js, `cpp-driver`  for C\C++, `bash-driver` for *sh)

## Relevant issues
 * initial discussion https://github.com/bblfsh/bash-driver/issues/39
 * [_usage pattern 2_](https://groups.google.com/forum/#!topic/bblfsh-dev/mo1o5d_CwnA) in client https://github.com/src-d/engine/issues/297
 * [_usage pattern 2_](https://groups.google.com/forum/#!topic/bblfsh-dev/mo1o5d_CwnA) in another client https://github.com/src-d/gitbase/issues/728

**Comment by smacker** [comment]
List of affected projects:

- jgit-spark-connector
  - src-ml
    - apollo
  - gemini
- gitbase
  - gitbase-web
    - engine
  - gitbase-spark-connector
  - gitbase-spark-connector-enterprise
- engine (`parse` command)
