### ISSUE TITLE
bblfshd process as PID 1 inside the container

### ISSUE THREAD

**Issue by bzz** [bblfsh/bblfshd#271]
While looking at #270 I noticed that `bblfshd` seems to be the [PID 1 process](https://github.com/bblfsh/bblfshd/blob/master/Dockerfile#L44) inside the container.

This issue is about changing that to something like https://github.com/Yelp/dumb-init or [something similar](https://github.com/krallin/tini/), with motivation well described at https://github.com/Yelp/dumb-init#why-you-need-an-init-system

What do you think?

**Comment by creachadair** [comment]
I agree. I think we should definitely not run `bblfshd` as PID 1, and I didn't realize that was the default.

Particularly for a process that runs a lot of child processes, getting the corner cases of reaping exits right is tricky. Most programs rely on having `init` as a fallback, and I bet this is also part of what causes https://github.com/bblfsh/bblfshd/issues/159.

**Comment by dennwc** [comment]
May be relevant: https://github.com/bblfsh/bblfshd/issues/159

**Comment by smola** [comment]
We use [tini](https://github.com/krallin/tini) in some of our projects. [See an example](https://github.com/src-d/gitbase/blob/90b377cdd1d03c43d59cdc335cde28dc82b8ae19/Dockerfile#L29).
