### ISSUE TITLE
bblfshd crashed and does not start after parsing millions of files

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/bblfshd#286]
I ran massive file parsing on 4 machines:

* `typos-1.infra.mining.prod.srcd.host`
* `typos-2.infra.mining.prod.srcd.host`
* `typos-3.infra.mining.prod.srcd.host`
* `typos-4.infra.mining.prod.srcd.host`

The pipeline was the same as in https://github.com/bblfsh/bblfshd/issues/270#issuecomment-486272814 How I started bblfshd:

```
docker run -d --name bblfshd --privileged -p 9432:9432 bblfsh/bblfshd
docker exec -it bblfshd bblfshctl driver install --all
```

All the versions correspond to #281 

Those instances ran for several days and then crashed. **`docker start bblfshd` starts the server and it immediately stops.** Each of the 4 machines has the same symptoms. The free space is fine: 75% of a 200GB volume is free.

Here are the logs:

* [typos-1](https://drive.google.com/open?id=1-w14XgsthOTKBmTPnUY2zg5IBljTVUCR)
* [typos-2](https://drive.google.com/open?id=1gaCTopQV7ptmhhc6QyWqaWgeSzxE9lhu)
* [typos-3](https://drive.google.com/open?id=1-W_Ajs0WI5lZowrHaP7qy_xt8tS12KPs)
* [typos-4](https://drive.google.com/open?id=1wFjJBUi_cVIBQk4zGLhplOFlrUQRIBt2)

Each file is ~4 gigs uncompressed.

I noticed that #270 persists. The access to my machines can be granted by @rporres upon request.

**Comment by dennwc** [comment]
```
error creating control listener: listen unix /var/run/bblfshctl.sock: bind: address already in use
```
Try removing the `/var/run/bblfshctl.sock` file on the server.

**Comment by dennwc** [comment]
It also shows a giant stack trace at the end. From a quick look, it may have been affected by https://github.com/bblfsh/bblfshd/issues/264.

**Comment by dennwc** [comment]
bblfshd v2.13.0 is out and should fix the crash, memory consumption and hopefully the CPU consumption as well.

Leaving this issue open, since we still need to solve an issue with the socket left after bblfshd crash.
