### ISSUE TITLE
Output UAST as true json

### ISSUE THREAD

**Issue by elizabethdinella** [bblfsh/bblfshd#296]
Hello,

The output of the UAST is not true json in that it's fields are not surrounded by quotes which makes it difficult to read and parse using python, javascript, etc.

Is there a way to output a true json object that can be loaded using a JSON library?

Thank you!

**Comment by dennwc** [comment]
Hi @elizabethdinella!

If you mean the output of `bblfshctl`, you are right, the output is not JSON, it's YAML. You can either use YAML parser or use a CLI that comes with a [Go client](https://github.com/bblfsh/go-client) to dump JSON instead.

**Comment by elizabethdinella** [comment]
Yes, thanks so much!
