### ISSUE TITLE
Read the logging level from an environment var

### ISSUE THREAD

**Issue by dpordomingo** [bblfsh/bblfshd#301]
caused by https://github.com/src-d/sourced-ce/issues/142

`bblfsh` logging level is only configurable through command arguments, so when directly using the docker image, configuring the logging level is not that simple as changing an env value from the outside.

**Comment by creachadair** [comment]
This seems like a reasonable request, but I would rather not have to re-implement this from first principles. What do other teams do, to support this use case?

**Comment by dpordomingo** [comment]
`gitbase` uses [`go-flags`](https://github.com/jessevdk/go-flags), as suggested by [our guides, about CLI tools](https://github.com/src-d/guide/blob/master/engineering/conventions/go.md#cli)

But newer `gitcollector`[[1]](https://github.com/src-d/gitcollector/blob/master/cmd/gitcollector/main.go#L13), `ghsync`[[2]](https://github.com/src-d/ghsync/blob/master/cmd/ghsync/main.go#L17) or `borges`[[3]](https://github.com/src-d/borges/blob/master/cli/borges/main.go#L17) use [`go-cli`](https://github.com/src-d/go-cli), that already wraps `go-flags` but also _reduces boilerplate code and helps in being more homogeneous with respect how our CLI work and look like_.

**Comment by creachadair** [comment]
@dpordomingo Thanks for the pointers! It looks like the important contribution from `go-cli` is bringing in `go-log`. @kuba-- has already started some work on migrating us over to use `go-log`, so hopefully we will be able to get environment support more easily.

**Comment by dpordomingo** [comment]
How is the migration going?

Would it be a simple alternative something like this [bblfsh/web#227](https://github.com/bblfsh/web/pull/227/files#diff-157b0e016d598e869df099dff16c041bR44)?
In summary, the logging level could be read from the environment and set if no `log-level` arg was passed at [cmd/bblfshd/main.go#L84](https://github.com/bblfsh/bblfshd/blob/master/cmd/bblfshd/main.go#L84)

Doing so, it would also unblock https://github.com/src-d/backlog/issues/1485

**Comment by creachadair** [comment]
> Would it be a simple alternative something like this [bblfsh/web#227](https://github.com/bblfsh/web/pull/227/files#diff-157b0e016d598e869df099dff16c041bR44)?
> In summary, the logging level could be read from the environment and set if no `log-level` arg was passed at [cmd/bblfshd/main.go#L84](https://github.com/bblfsh/bblfshd/blob/master/cmd/bblfshd/main.go#L84)
> 
> Doing so, it would also unblock [src-d/backlog#1485](https://github.com/src-d/backlog/issues/1485)

That seems like a reasonable workaround to me. It looks like the work that @kuba-- did makes this a simple enough change to make, too. See #327.

**Comment by bzz** [comment]
Going to close this one, as it seems to be fixed by #327 and released under [v2.16.1](https://github.com/bblfsh/bblfshd/releases/tag/v2.16.1).

But please, feel free to re-open if that is not the case!
