### ISSUE TITLE
Refactor scalability mechanism - make it _container agnostic_ 

### ISSUE THREAD

**Issue by kuba--** [bblfsh/bblfshd#313]
Based on [Q&A session](https://github.com/src-d/minutes/blob/master/languages/2019-09-24-qa-session.md), the current driver container management approach in Babelfish has some potential problems with compatibility across different OS.

We agreed to switch to docker API as a standard runtime for drivers.

**Comment by kuba--** [comment]
It's also partly related to https://github.com/bblfsh/bblfshd/issues/293

**Comment by dennwc** [comment]
Also note that one of the considered options is [containerd](https://containerd.io/), which is used by Docker under the hood. It's not as low-level as libcontainer and is more similar to Docker itself in this regard.

But running in Docker first makes a lot of sense.

**Comment by kuba--** [comment]
The goal of this task is to  get rid of `libcontainer` runtime from `bblfshd`, expose common _Driver's API_  in such a way, that we can internally integrate `docker`and/or `containerd`.

We can split `Driver interface`  into two interfaces: `Driver` and `Container`
```go
type Driver interface {
    Create (lang string, img string, o Options) (Container, error)
    Service() protocol1.ProtocolServiceClient
    ServiceV2() protocol2.DriverClient
}

type Container interface {
    ID() string
    Start(ctx context.Context) error
    Stop() error
    Status() (protocol.Status, error)
    State() (*protocol.DriverInstanceState, error)
}
```

Two independent _sub-packages_ - `docker` and `containerd`will implement  both interfaces. We can import driver implementations in the same way how we import `db` drivers:
```go
import _ github.com/bblfsh/bblfshd/docker
```

---
Examples of implementation differences

###  Create (lang string, img string, o Options)
- Docker
```go
cli, err := client.NewClientFromEnv()
reader, err := cli.ImagePull(img)
resp, err := cli.ContainerExecCreate(ctx, img, config) 
```

- Containerd
```go
client, err := containerd.New("/tmp/rpc.sock")
ctx := namespaces.WithNamespace(context.Background(), "bblfshd")
image, err := client.Pull(ctx, img, containerd.WithPullUnpack)
container, err := client.NewContainer(
		ctx,
		"driver",
		containerd.WithNewSpec(oci.WithImageConfig(image)),
	)
```

### Start(ctx context.Context) error
- Docker
```go
err := cli.ContainerExecStart(ctx, execID, config)
```

- Containerd
```go
task, err := container.NewTask(ctx, cio.NewCreator(cio.WithStdio))
```

### Stop() error
- Docker
```go
err := cli.ContainerStop(ctx, container.ID, nil);
statusCh, errCh := cli.ContainerWait(ctx, resp.ID, container.WaitConditionNotRunning)
	select {
	case err := <-errCh:
		if err != nil {
			panic(err)
		}
	case <-statusCh:
	}
```

- Containerd
```go
task.Delete(ctx)
```

### Status() (protocol.Status, error)
### State() (*protocol.DriverInstanceState, error)
- Docker
```go
resp, err := cli.ContainerInspect(ctx, containerID) 
resp.State.Status
```

- Containerd
```go
s, err := task.Process.Status(ctx)
s.Status
```
---
@bblfsh/maintainers - let me know what do you think.

**Comment by dennwc** [comment]
@kuba-- Looks good overall, but I have a few questions.

1) Why `Service` and `ServiceV2` are on the `Driver` and not on the `Container`?

2) We probably don't need `lang` - it should be inferred from the image itself (either from metadata or from a manifest inside the image).

3) Previously we supported all kinds of driver image formats. We should at least note what formats will be no longer supported after this change.

**Comment by kuba--** [comment]
@dennwc:

1) Mainly because it looks these services are not related to container or any process running inside container. So far, we have:
```go

// Service returns the client using the grpc connection.
func (i *DriverInstance) Service() protocol1.ProtocolServiceClient {
	return i.srv1
}

// ServiceV2 returns the client using the grpc connection.
func (i *DriverInstance) ServiceV2() protocol2.DriverClient {
	return i.srv2
}
```

where `DriverInstance` contains:
```go
i.srv1 = protocol1.NewProtocolServiceClient(conn)
i.srv2 = protocol2.NewDriverClient(conn)
```

Container interface should have only functions which can communicate with processes running inside a container, specific per implementation (docker, containerd).

---
2) Makes sense. I'll fix it.
---
3) Good to know. Totally forgot about it. We should create a related issue to update docs.

**Comment by creachadair** [comment]
Overall this seems like a good start. My only request for now is that we extract some of this discussion into a design doc, so that we can have a record of the eventual state of the API we plan to implement.

**Comment by kuba--** [comment]
@bblfsh/maintainers 
I moved this design to the doc: https://docs.google.com/document/d/1671ApmxFCOmerVKloVC6Q6j8BsJr8xZHbhuE40ZK-as/edit?usp=sharing

So far, there is nothing more (just copied the current proposal), but we can continue discussion in the doc (like @creachadair suggested).

**Comment by smola** [comment]
Please, consider how this will run in a Kubernetes pod. If we use Docker backend, we might effectively need a Docker in Docker setup. In any case, creating a runtime interface sounds great and I hope it might help with rootless containers at some point.

**Comment by creachadair** [comment]
We discussed this a bit more in https://github.com/src-d/minutes/pull/778. While there are important design elements we still need to investigate, we broadly agreed that our target state should:

1. Separate scalability support from basic operation,
2. Delegate scalability to other components (e.g., Kubernetes), but
3. Support running locally for simple workloads without requiring users to install complex dependences (e.g., minikube),
4. Not require privileged containers (per [above](#issuecomment-542143430), see also #153 for context), and
5. (Nice to have, if practical) Be runnable locally even without containerization.

Some of the issues we'll need to cover are in the minutes and the associated doc.

**Comment by kuba--** [comment]
I made this task as epic/umbrella task. Following sub-tasks may also be _tracking_ tasks, so if it's needed we can split them ask well, as needed:

- [ ] https://github.com/bblfsh/bblfshd/issues/319
- [ ] https://github.com/bblfsh/bblfshd/issues/320
- [ ] https://github.com/bblfsh/bblfshd/issues/321
- [ ] https://github.com/bblfsh/bblfshd/issues/322
