### ISSUE TITLE
Ongoing maintenance of the Babelfish project

### ISSUE THREAD

**Issue by creachadair** [bblfsh/bblfshd#332]
I have unarchived this repository and created this issue to discuss a possible handoff of ownership of the Babelfish project.

The Wildcard (@w6d-io) team has been using Babelfish for various purposes for some time now. Since the original source{d} team is no longer available to update it, @grumbach and @cordiers asked if we would consider allowing them to take over its maintenance and development.

I'm inclined to agree, but I wanted to give the other designated owners of the organization a chance to weigh in before I make a call either way. If you have any questions, comments, or concerns, please add them to this issue.

Cc: @dennwc, @eiso, @rpau

**Comment by dennwc** [comment]
I fully agree with this proposal. I would also like the project to continue and will try to dedicate some time for maintaining it as well.

**Comment by kuba--** [comment]
I'm still in this org. what means that I care.
So, go for it!

**Comment by grumbach** [comment]
Thanks guys! We're so glad this project still has such a great community around it! 🥇

**Comment by creachadair** [comment]
It sounds like we mostly have consensus here. As a first step, I just invited @grumbach and @cordiers to the organization. Unless there is any objection, I would also like to promote you both to project owners.

**Comment by creachadair** [comment]
Having heard no further comments, most notably having heard no further objections, I will now promote @grumbach and @cordiers to owners.

**Comment by creachadair** [comment]
I believe we've now resolved this question, so I'm closing the issue. Feel free to re-open if you believe we need further discussion, or file new issues for related topics.
