### ISSUE TITLE
Is bblfshd dead?

### ISSUE THREAD

**Issue by maddin79** [bblfsh/bblfshd#346]
Is this project still maintained? The website is down and no progress over the last month.

Best
Martin

**Comment by david972** [comment]
Hi we’ve got the ownership but our team has been reduced 
So for now it’s not really maintained 
But any help is welcomed

**Comment by maddin79** [comment]
Hey David, 

I hope you will find the time to go on with this. It is a great project. Unfortunately I have no experience in Go and have no time to dig into it. Sorry

**Comment by kuba--** [comment]
@maddin79 - I worked for bblfshd project for a while, so maybe I can help. Do you have any particular use case which you want to discuss?
